version: "3"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - survey-backend-mysql-volume:/var/lib/mysql
      # - ./db/dump:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 500m
          cpus: "0.3"
volumes:
  survey-backend-mysql-volume: {}
