runtime: ruby25
service: default
instance_class: F1
entrypoint: bundle exec rails s -e production
env_variables:
  IS_GAE: true
  RAILS_SERVE_STATIC_FILES: true
includes:
  - env.yaml
automatic_scaling:
  target_cpu_utilization: 0.70
  target_throughput_utilization: 0.70
  min_instances: 0
  max_idle_instances: 1
  min_idle_instances: 0
  min_pending_latency: 1000ms
  max_pending_latency: automatic
  max_concurrent_requests: 80
